### ISSUE TITLE
Clean up vector store lab

### ISSUE THREAD

**Issue by denniszielke** [Azure/intro-to-intelligent-apps#108]
Merge 03 and 04
Clean up duplicates in Qdrant, Mongo and AI
Move up 05
Delete 06 lab
```[tasklist]
### Tasks
- [ ] Clean up Qdrant vector store lab
- [x] Move lab 05 to 04
- [x] Delete lab 06
- [ ] Move and cleanup AI Search Lab
- [ ] Move and cleanup Mongo Lab
```
